In [1]:
import csv

In [2]:
MonthlySales = []

In [3]:
with open('data/MonthlySales.csv', 'r') as f:
    reader = csv.DictReader(f)
    for row in reader:
        MonthlySales.append(row)

In [4]:
for a in MonthlySales:
    print a

{'sales': '14236.90', 'month': '2013-01-01'}
{'sales': '4519.89', 'month': '2013-02-01'}
{'sales': '55691.01', 'month': '2013-03-01'}
{'sales': '28295.35', 'month': '2013-04-01'}
{'sales': '23648.29', 'month': '2013-05-01'}
{'sales': '34595.13', 'month': '2013-06-01'}
{'sales': '33946.39', 'month': '2013-07-01'}
{'sales': '27909.47', 'month': '2013-08-01'}
{'sales': '81777.35', 'month': '2013-09-01'}
{'sales': '31453.39', 'month': '2013-10-01'}
{'sales': '78628.72', 'month': '2013-11-01'}
{'sales': '69545.62', 'month': '2013-12-01'}
{'sales': '18174.08', 'month': '2014-01-01'}
{'sales': '11951.41', 'month': '2014-02-01'}
{'sales': '38726.25', 'month': '2014-03-01'}
{'sales': '34195.21', 'month': '2014-04-01'}
{'sales': '30131.69', 'month': '2014-05-01'}
{'sales': '24797.29', 'month': '2014-06-01'}
{'sales': '28765.33', 'month': '2014-07-01'}
{'sales': '36898.33', 'month': '2014-08-01'}
{'sales': '64595.92', 'month': '2014-09-01'}
{'sales': '31404.92', 'month': '2014-10-01'}
{'sales': '75972.56', 'month': '2014-11-01'}
{'sales': '74919.52', 'month': '2014-12-01'}
{'sales': '18542.49', 'month': '2015-01-01'}
{'sales': '22867.71', 'month': '2015-02-01'}
{'sales': '51186.22', 'month': '2015-03-01'}
{'sales': '39248.59', 'month': '2015-04-01'}
{'sales': '56691.08', 'month': '2015-05-01'}
{'sales': '39430.44', 'month': '2015-06-01'}
{'sales': '38440.76', 'month': '2015-07-01'}
{'sales': '33265.56', 'month': '2015-08-01'}
{'sales': '72908.11', 'month': '2015-09-01'}
{'sales': '56463.13', 'month': '2015-10-01'}
{'sales': '82192.32', 'month': '2015-11-01'}
{'sales': '97237.42', 'month': '2015-12-01'}
{'sales': '44703.14', 'month': '2016-01-01'}
{'sales': '20301.13', 'month': '2016-02-01'}
{'sales': '58872.35', 'month': '2016-03-01'}
{'sales': '36521.54', 'month': '2016-04-01'}
{'sales': '44261.11', 'month': '2016-05-01'}
{'sales': '52981.73', 'month': '2016-06-01'}
{'sales': '45264.42', 'month': '2016-07-01'}
{'sales': '63120.89', 'month': '2016-08-01'}
{'sales': '87866.65', 'month': '2016-09-01'}
{'sales': '77776.92', 'month': '2016-10-01'}
{'sales': '118447.83', 'month': '2016-11-01'}
{'sales': '83829.32', 'month': '2016-12-01'}

In [5]:
#print keys
for a in MonthlySales:
    print a.keys()

['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']
['sales', 'month']

In [6]:
#print keys and values
for a in MonthlySales:
    for key, value in a.items():
        print key + ": ", value
    print '\n'

sales:  14236.90
month:  2013-01-01


sales:  4519.89
month:  2013-02-01


sales:  55691.01
month:  2013-03-01


sales:  28295.35
month:  2013-04-01


sales:  23648.29
month:  2013-05-01


sales:  34595.13
month:  2013-06-01


sales:  33946.39
month:  2013-07-01


sales:  27909.47
month:  2013-08-01


sales:  81777.35
month:  2013-09-01


sales:  31453.39
month:  2013-10-01


sales:  78628.72
month:  2013-11-01


sales:  69545.62
month:  2013-12-01


sales:  18174.08
month:  2014-01-01


sales:  11951.41
month:  2014-02-01


sales:  38726.25
month:  2014-03-01


sales:  34195.21
month:  2014-04-01


sales:  30131.69
month:  2014-05-01


sales:  24797.29
month:  2014-06-01


sales:  28765.33
month:  2014-07-01


sales:  36898.33
month:  2014-08-01


sales:  64595.92
month:  2014-09-01


sales:  31404.92
month:  2014-10-01


sales:  75972.56
month:  2014-11-01


sales:  74919.52
month:  2014-12-01


sales:  18542.49
month:  2015-01-01


sales:  22867.71
month:  2015-02-01


sales:  51186.22
month:  2015-03-01


sales:  39248.59
month:  2015-04-01


sales:  56691.08
month:  2015-05-01


sales:  39430.44
month:  2015-06-01


sales:  38440.76
month:  2015-07-01


sales:  33265.56
month:  2015-08-01


sales:  72908.11
month:  2015-09-01


sales:  56463.13
month:  2015-10-01


sales:  82192.32
month:  2015-11-01


sales:  97237.42
month:  2015-12-01


sales:  44703.14
month:  2016-01-01


sales:  20301.13
month:  2016-02-01


sales:  58872.35
month:  2016-03-01


sales:  36521.54
month:  2016-04-01


sales:  44261.11
month:  2016-05-01


sales:  52981.73
month:  2016-06-01


sales:  45264.42
month:  2016-07-01


sales:  63120.89
month:  2016-08-01


sales:  87866.65
month:  2016-09-01


sales:  77776.92
month:  2016-10-01


sales:  118447.83
month:  2016-11-01


sales:  83829.32
month:  2016-12-01